### ISSUE TITLE
Bestmomo installer not working on laravel 5.4 [with username field (unique) of users table]

### ISSUE THREAD

**Issue by shahindeveloper** [bestmomo/laravel5-3-installer#1]
When type the username and database name and submit from loacalhost it showing the bellow problem...
how can i solve this isssues...please help!!!!!
![screenshot-2017-12-14 laravel installer](https://user-images.githubusercontent.com/13506070/33977865-283fea30-e0c7-11e7-93a0-0edb9cbb3717.png)

**Comment by bestmomo** [comment]
Looks like you didn't enter corrects paramaters for MySql access.

**Comment by shahindeveloper** [comment]
If i use Schema::defaultStringLength(191); on boot function of the App ServiceProvider it is not not working and shows the above error. If i removed the  Schema::defaultStringLength(191); from boot function then it works. I am using Mysql+PHP 7.0.10

**Comment by bestmomo** [comment]
If you use MySQL v5.7.7 or higher you dont have to add the default string length in provider.

**Comment by shahindeveloper** [comment]
**Installer not working on php version 7.0.10. It shows bellow error**

[2018-04-27 09:01:50] local.ERROR: PDOException: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) in D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:68
Stack trace:
#0 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(68): PDO->__construct('mysql:host=127....', '', '', Array)
#1 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=127....', '', '', Array)
#2 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=127....', Array, Array)
#3 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(183): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#5 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Database\Connection.php(883): call_user_func(Object(Closure))
#6 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Database\Connection.php(904): Illuminate\Database\Connection->getPdo()
#7 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Database\Connection.php(392): Illuminate\Database\Connection->getReadPdo()
#8 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Database\Connection.php(318): Illuminate\Database\Connection->getPdoForSelect(true)
#9 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Database\Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('select * from i...', Array)
#10 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Database\Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
#11 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Database\Connection.php(326): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#12 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Database\Schema\MySqlBuilder.php(18): Illuminate\Database\Connection->select('select * from i...', Array)
#13 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Database\Migrations\DatabaseMigrationRepository.php(154): Illuminate\Database\Schema\MySqlBuilder->hasTable('migrations')
#14 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(544): Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists()
#15 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\MigrateCommand.php(96): Illuminate\Database\Migrations\Migrator->repositoryExists()
#16 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\MigrateCommand.php(62): Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase()
#17 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#18 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(29): call_user_func_array(Array, Array)
#19 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#20 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#21 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Container\Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#22 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Console\Command.php(182): Illuminate\Container\Container->call(Array)
#23 D:\wamp\www\fundly_demo\vendor\symfony\console\Command\Command.php(262): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#24 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Console\Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#25 D:\wamp\www\fundly_demo\vendor\symfony\console\Application.php(888): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#26 D:\wamp\www\fundly_demo\vendor\symfony\console\Application.php(224): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#27 D:\wamp\www\fundly_demo\vendor\symfony\console\Application.php(125): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#28 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Console\Application.php(141): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#29 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(220): Illuminate\Console\Application->call('migrate', Object(Illuminate\Support\Collection), NULL)
#30 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(221): Illuminate\Foundation\Console\Kernel->call('migrate')
#31 D:\wamp\www\fundly_demo\vendor\bestmomo\laravel5-3-installer\src\Http\Controllers\DatabaseController.php(43): Illuminate\Support\Facades\Facade::__callStatic('call', Array)
#32 [internal function]: Bestmomo\Installer\Http\Controllers\DatabaseController->store(Object(Illuminate\Http\Request), Object(Bestmomo\Installer\Repositories\EnvironmentRepository))
#33 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(55): call_user_func_array(Array, Array)
#34 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('store', Array)
#35 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Bestmomo\Installer\Http\Controllers\DatabaseController), 'store')
#36 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Route.php(160): Illuminate\Routing\Route->runController()
#37 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(572): Illuminate\Routing\Route->run()
#38 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 D:\wamp\www\fundly_demo\app\Http\Middleware\SetSiteSetting.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\SetSiteSetting->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 D:\wamp\www\fundly_demo\app\Http\Middleware\PreventHistory.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\PreventHistory->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 D:\wamp\www\fundly_demo\app\Http\Middleware\Locale.php(26): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\Locale->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#55 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#58 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#61 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#62 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#63 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#64 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#65 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#66 D:\wamp\www\fundly_demo\vendor\barryvdh\laravel-debugbar\src\Middleware\Debugbar.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#67 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#70 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#71 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#73 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#74 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 D:\wamp\www\fundly_demo\app\Http\Middleware\PreventHistory.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#76 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\PreventHistory->handle(Object(Illuminate\Http\Request), Object(Closure))
#77 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#78 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#79 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#80 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#81 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#82 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#83 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#84 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#85 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#86 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#87 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#88 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#89 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#90 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#91 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#92 D:\wamp\www\fundly_demo\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#93 D:\wamp\www\fundly_demo\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#94 {main}  
[2018-04-27 09:01:50] local.INFO: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) (SQL: select * from information_schema.tables where table_schema =  and table_name = migrations)
